Repository launchbadge/sqlx, pull requests merged in 2020-12, with the labels that each got.

#506 Support workspaces for offline feature
  Cargo.lock
  sqlx-cli/src/lib.rs
  sqlx-cli/src/opt.rs
  sqlx-cli/src/prepare.rs
  sqlx-macros/Cargo.toml
  sqlx-macros/src/query/mod.rs
Labels: waiting for author

#761 Make quickstart actually quick
  README.md
Labels: example, waiting for author

#786 Add new example for migration
  sqlx-core/src/migrate/migrator.rs
Labels: example, waiting for author

#850 sqlite synchronous setting
  sqlx-core/src/sqlite/mod.rs
  sqlx-core/src/sqlite/options/connect.rs
  sqlx-core/src/sqlite/options/mod.rs
  sqlx-core/src/sqlite/options/synchronous.rs
Labels: sqlite, waiting for author

#925 Fix broken link in Transaction docs
  sqlx-core/src/transaction.rs
Labels: waiting for author
