Repository launchbadge/sqlx, pull requests merged in 2025-07, with the labels that each got.

#3674 Implement `Decode`, `Encode` and `Type` for `Box`, `Arc`, `Cow` and `Rc`
  sqlx-core/src/decode.rs
  sqlx-core/src/encode.rs
  sqlx-core/src/types/mod.rs
  sqlx-mysql/src/types/bytes.rs
  sqlx-mysql/src/types/str.rs
  sqlx-postgres/src/types/bytes.rs
  sqlx-postgres/src/types/str.rs
  sqlx-sqlite/src/types/bytes.rs
  sqlx-sqlite/src/types/str.rs
  tests/mysql/types.rs
  tests/postgres/types.rs
  tests/sqlite/types.rs
Labels: breaking

#3613 fix: `RawSql` lifetime issues
  sqlx-core/src/raw_sql.rs
  tests/sqlite/sqlite.rs
Labels: breaking

#3526 Return &mut Self from the migrator set_ methods
  sqlx-core/src/migrate/migrator.rs
Labels: breaking

#3867 sqlx-postgres: Bump etcetera to 0.10.0
  Cargo.lock
  sqlx-postgres/Cargo.toml
Labels: breaking:MSRV

#3924 breaking(mysql): assume all non-binary collations compatible with `str`
  .github/workflows/sqlx.yml
  Cargo.lock
  Cargo.toml
  sqlx-core/src/raw_sql.rs
  sqlx-mysql/src/collation.rs
  sqlx-mysql/src/connection/establish.rs
  sqlx-mysql/src/connection/mod.rs
  sqlx-mysql/src/connection/stream.rs
  sqlx-mysql/src/connection/tls.rs
  sqlx-mysql/src/options/connect.rs
  sqlx-mysql/src/options/mod.rs
  sqlx-mysql/src/protocol/connect/handshake_response.rs
  sqlx-mysql/src/protocol/connect/ssl_request.rs
  sqlx-mysql/src/protocol/text/column.rs
  sqlx-mysql/src/type_info.rs
  sqlx-mysql/src/types/bool.rs
  sqlx-mysql/src/types/str.rs
  sqlx-mysql/src/types/uint.rs
  tests/docker-compose.yml
  tests/mysql/macros.rs
  tests/mysql/mysql.rs
  tests/mysql/setup-mariadb.sql
Labels: db:mysql, breaking
